import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Button } from '../stories/Button';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
	return (
		<div className={styles.container}>
			<Head>
				<title>Storybook Practice</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<div>
				STORYBOOK PRACTICE
				<Button label='SIGN UP' size='large' />
			</div>
		</div>
	);
};

export default Home;
